### ISSUE TITLE
handling padding when computing scaling for cost matrices.

### ISSUE THREAD

**Issue by marcocuturi** [ott-jax/ott#100]
The segmented approaches to pad efficiently point clouds rely on padding with "default" (e.g. zero) vectors. These padded vectors create spurious entries in cost matrices, but when running Sinkhorn, these entries are ignored thanks to the fact that these entries have 0 weights (in the respective `a` and `b` weight vectors). However, these entries would play a role when computing scalings (such as mean cost). 

A possible approach would be to redefine some of those statistics (e.g. max, mean etc..) to only apply to entries that have a positive weight (e.g. C_ij is considered iff a_i b_j >0). For the mean cost, the mean might be weighted by a_i b_j as well.

**Comment by michalk8** [comment]
> A possible approach would be to redefine some of those statistics (e.g. max, mean etc..) to only apply to entries that have a positive weight (e.g. C_ij is considered iff a_i b_j >0). For the mean cost, the mean might be weighted by a_i b_j as well.

I think partial solution to this can be found in #99 , where I define a subset method.
In this case, we could implement `inv_scale_cost` in geometries as:
```python
@property
def inv_scale_cost(self) -> float:
    if self._src_ixs None and self._tgt_ixs is None:
        return self._inv_scale_cost
    return self.subset(self._src_ixs, self._tgt_ixs)._inv_scale_cost

@property
def _inv_scale_cost(self) -> float:  # old `inv_scale_cost`, now private
    if isinstance(self._scale_cost, float):
      return 1.0 / self._scale_cost
    ...
```
However, this would require we save the extra valid `{src,tgt}_ixs`, which I'm ok with (better than passing them in each function).

**Comment by marcocuturi** [comment]
Thanks Ersi, Michal. 

Michal: for the fix you propose I feel the issue here is computing `self._scale_cost`, which, typically, when considering a mean distance will be problematic because of the padding. I think it could be easier overall to update the scale cost methods to incorporate a set of indices on which statistics should be considered. This could in some case fallback on `subset` as you defined it, but also possibly something slightly more complicated.

**Comment by michalk8** [comment]
> Michal: for the fix you propose I feel the issue here is computing self._scale_cost, which, typically, when considering a mean distance will be problematic because of the padding. I

I think I might be missing something, but `self._scale_cost` is just the flag which tells how to compute the inverse scaling (Laetitia changed the naming a while back).
Unless you want to have something very generic, like `(n, m)` boolean mask for kernels/costs (a trouble finding a use case ATM), I'd say the approach above should be sound for `Geometry/LRCGeometry/PointCloud` without much modification.

**Comment by marcocuturi** [comment]
You are right, I think the fix you propose is very good! It's a bit of an open debate to figure out whether the normalization should be weight dependent or not (i.e. should we take into account `a` and `b`, and not just their supports) but I think what makes for now this solution more preferable is that this can be entirely handled at the level of the padding blocks.
