### ISSUE TITLE
Add CI for notebooks

### ISSUE THREAD

**Issue by michalk8** [ott-jax/ott#104]
There were 2 notebooks which I found were not runnable in #99 . Think it's a good idea to test/regenerate notebooks on the CI to make sure they are always up-to-date.

**Comment by marcocuturi** [comment]
Thanks Michal, this is true, and would save us a lot of bad user experience when we modifiy APIs. A minor issue is that some of the colab are "abridged", typically they only contain part of the code that is needed to have them run. So I am guessing we should drop colabs altogether, and have this turned into a .py script with sphynx?

**Comment by michalk8** [comment]
> So I am guessing we should drop colabs altogether, and have this turned into a .py script with sphynx?

This is orthogonal to Colab/how the notebooks are saved (.ipynb vs .py). Would go for something like https://github.com/chrisjsewell/pytest-notebook.
Would leave the regeneration explicitly on the dev (simpler to do), unless you want to have automatic commits on from the CI on opened PRs that do it for you (personally I dislike this).
