### ISSUE TITLE
Wasserstein distance gets multiplied by 2 in ``neuraldual.py``

### ISSUE THREAD

**Issue by lucaeyring** [ott-jax/ott#110]
Hello,

In ``neuraldual.py`` the computed final Wasserstein distance gets multiplied by ``2``, see: https://github.com/ott-jax/ott/blob/main/ott/core/neuraldual.py#L397

I don't understand why this is done here. As far as I see, there is no *2 in the [original Makkuva et al. formulation](https://arxiv.org/pdf/1908.10962.pdf), e.g. equation 6.

**Comment by marcocuturi** [comment]
Thanks a lot for your comment Luca! 

This is a good point. I think this was a convention choice.

In the literature, $W_2^2$ is usually defined using the $\|x-y\|^2$ distance. In the Makkuva paper (and most other papers that rely on the Brenier theorem), the cost is normalized to $\frac{1}{2}\|x-y\|^2$, which makes life easier.

It's worth clarifying this in the docstring, thanks a lot for your comment.

**Comment by lucaeyring** [comment]
Thanks a lot for the detailed answer!
