### ISSUE TITLE
Removing `make` functions

### ISSUE THREAD

**Issue by michalk8** [ott-jax/ott#131]
Such as [here](https://github.com/ott-jax/ott/blob/main/ott/core/sinkhorn_lr.py#L539). I think they are unnecessary and provide a maintenance overhead.

**Comment by marcocuturi** [comment]
Yes I agree. They were mostly added for backward compatibility, notably for `sinkhorn`, since we gradually changed the API to more generic objects, notably for momentum and acceleration. But I would be in favor of removing them as well.

**Comment by michalk8** [comment]
I'd also make further breaking changes before the geometry/solver refactoring - removing `jit` option (for jitting the iteration function) + remove high-level functions (e.g., `sinkhorn`, `gromov_wasserstein`, ...) and keep the solver/problem/output interface only.

**Comment by marcocuturi** [comment]
I think removing them completely could be challenging for some users and backward compatibility, however, I agree we should phase them out in the current notebooks

**Comment by michalk8** [comment]
moving the conversation to #170
