### ISSUE TITLE
type not understood error when calling ott.tools.plot.Plot() in high dimensional data

### ISSUE THREAD

**Issue by anisioti** [ott-jax/ott#139]
Hello, 

I have realized that there is the following error happening when calling ` ott.tools.plot.Plot() ` for jax arrays with dimension higher than 2. 

While searching, I realized that the error is happening in the `bidimensional()` function called when the data are high dimensional in order to project them in 2 dimensions. 

More specifically the error is happening when we use `scipy.sparse.linalg.svds with jnp.concatenate ` (jax device arrays). If the input vectors are passed like nupmy arrays the function works properly. 

**To Reproduce**

For reproducing the error you can run the initial provided example 
```
  import jax
  import jax.numpy as jnp
  from ott.tools import transport
  # Samples two point clouds and their weights.
  rngs = jax.random.split(jax.random.PRNGKey(0),4)
  n, m, d = 12, 14, 20
  x = jax.random.normal(rngs[0], (n,d)) + 1
  y = jax.random.uniform(rngs[1], (m,d))
  a = jax.random.uniform(rngs[2], (n,))
  b = jax.random.uniform(rngs[3], (m,))
  a, b = a / jnp.sum(a), b / jnp.sum(b)
  # Computes the couplings via Sinkhorn algorithm.
  ot = transport.solve(x, y, a=a, b=b)
  P = ot.matrix
```
where **d = 20** is the dimension of the vectors instead of 2 in the original example. 

Then run the following: 
```
plott = ott.tools.plot.Plot()
_ = plott(ot)
```

The same result happens when we run 
```
scipy.sparse.linalg.svds(y, k=2)
# y is jax DeviceArray here 
```
But is solved if we run 

```
scipy.sparse.linalg.svds(np.array(y), k=2)
# here it is converted to numpy array
```

**Comment by anisioti** [comment]
Hello Marco! Thank you very much for your reply! Yes sure I can send a PR. 

I have one more question regarding this plot. When doing this change mentioned above the `bidimensional` function works but then there is the exception `So far we only plot PointCloud geometry`. I was wondering if this exception is needed (it comes from the ` _scatter` function on the same file). When removing it the plot works fine when ot has type  
` ott.tools.transport.Transport` (as it is on the initial example)
Also when running the simple example where d = 2 then the exception is not raised even if ot has the same type.

**Comment by marcocuturi** [comment]
thanks for raising these issues Athina... What you say shows even more clearly that this part was not properly tested  😅 sorry for these bugs. If you think this can be fixed easily, we'd love to have your PR! otherwise, we can look into a solution.

**Comment by marcocuturi** [comment]
Hi Athina, I just took a closer look, and copy/pasted your code into a colab:

https://colab.research.google.com/drive/1saJT3E2br-SwQvUTebufr5NnbxkeJpzp?usp=sharing

it seems the conversion is handled automatically, and I do not see the other error (`so far we ...`). Any update on your side?
