### ISSUE TITLE
Functional way to run Sinkhorn algorithm via `sinkhorn.sinkhorn` seems to be significantly slower that `sinkhorn.Sinkhorn()(...)`

### ISSUE THREAD

**Issue by theouscidda6** [ott-jax/ott#202]
According to the different notebooks, there are two ways to run Sinkhorn, which seem to be equivalent.

For example, suppose we have two point clouds `x` and `y` for which we want to calculate the corresponding `reg_ot_cost`. 
The two ways to compute this `reg_ot_cost` are:

```
THRESHOLD = 1e-3
MAX_ITERATIONS = 2_000
EPSILON = 1e-3
cost_fn = SqEuclidean()

def get_reg_cost_1(x, y):
    "Functional."
    cost_matrix = cost_fn.all_pairs(x, y)
    geom = geometry.Geometry(cost_matrix, epsilon=EPSILON)
    return sinkhorn.sinkhorn(
        geom,
        **{"threshold": THRESHOLD,
           "max_iterations": MAX_ITERATIONS} # sinkhorn kwargs 
        ).reg_ot_cost
    
def get_reg_cost_2(x, y):
    "Via Sinkhorn class."
    cost_matrix = cost_fn.all_pairs(x, y)
    geom = geometry.Geometry(cost_matrix, epsilon=EPSILON)
    return sinkhorn.Sinkhorn(
            threshold=THRESHOLD,
            max_iterations=MAX_ITERATIONS,
        )(linear_problem.LinearProblem(geom)).reg_ot_cost
```

What I understand (and which may be wrong):
The only thing that differs in these two ways of running the Sinkhorn algorithm, is that in the first one, we don't directly instantiate an element of the `Sinkhorn` class, but it will be done inside the `sinkhorn.sinkhorn` function, by the `make` function. 
Whereas in the second one, we instantiate an object of the `Sinkhorn` class and then we call this object to run the Sinkhorn algorithm. 
It seems that the first way is more "functional" than the second. 

Both of these ways are used in notebooks, for example the first is used in the notebook "Meta OT and Sinkhorn Initializers" https://ott-jax.readthedocs.io/en/latest/notebooks/MetaOT.html and the second is used in the notebook "Point clouds" https://ott-jax.readthedocs.io/en/latest/notebooks/point_clouds.html (which seems to have been updated recently).

However, they give very different running times: the first seems to be significantly slower than the second. 

If I run the following code on my machine:
```
# generate data
rng = random.PRNGKey(0)
rngs = random.split(rng, 2)
NUM_SAMPLES, DIM = 1024, 10
x = random.uniform(rng, minval=-1, maxval=1, shape=(NUM_SAMPLES, DIM))
y = random.normal(rng, shape=(NUM_SAMPLES, DIM))

%timeit -n100 -r3 get_reg_cost_1(x, y).block_until_ready()
%timeit -n100 -r3 get_reg_cost_2(x, y)
```

I get that `get_reg_cost_1` is more than 70 times slower that `get_reg_cost_2`:
```
720 ms ± 4.1 ms per loop (mean ± std. dev. of 3 runs, 100 loops each)
10 ms ± 319 µs per loop (mean ± std. dev. of 3 runs, 100 loops each)
```

So I guess I'm making a mistake somewhere in the use of `solvers`? Or if not, how can we explain this difference? 

Thank you very much!

**Comment by michalk8** [comment]
Hi @theouscidda6, I assume you're using the latest release on PyPI. The reason is (mostly likely) because the functional way of running sinkhorn has slightly different defaults (namel,y `jit=False` wheras in `Sinkhorn` solver class it's `True` by default).
In #192, the default jitting has been completely removed and user will require to jit the functions themselves. We also plan on deprecating the functional interface soon (will raise a warning in the future release).

**Comment by theouscidda6** [comment]
Yes, I'm using the latest version.
Okay, that's very clear, thank you very much!
So I have to understand that the second version is automatically jitted, so if I want to use it in a more complex pipeline, that will be jitted "on top" of this block, I should remove the default argument `jit=True` right? In order to avoid `jit`of `jit`.

**Comment by michalk8** [comment]
> I should remove the default argument jit=True right? In order to avoid jitof jit.

Yes, you should try to jit the outermost level of your function so that `jax` can have a chance at doing better optimizations (it will also incur some overhead because the inner/outer functions will have to be traced twice).

**Comment by theouscidda6** [comment]
Okay, fine, thank you. 
I tried using the second version with `jit=False` and it indeed gives ~700 ms as the first version. So your diagnosis was right!
Finally, you seem to be saying that I should prefer the second version (with `sinkhorn.Sinkhorn()`) than the first (functional, with `sinkhorn.sinkhorn`) version, right? Why? Just because of these different default arguments?

**Comment by michalk8** [comment]
> Why? Just because of these different default arguments?

No, we will be deprecating that API soon (see #204) since it builds on top of the `sinkhorn.Sinkhorn` solver and doesn't provide much additional convenience/utility.

**Comment by theouscidda6** [comment]
Okay, thank you very much for your quick answers!
