### ISSUE TITLE
We shouldn't pass a one-rank OT matrix as initialization

### ISSUE THREAD

**Issue by othmanesebbouh** [ott-jax/ott#208]
https://github.com/ott-jax/ott/blob/2f5242be393cda9a8ce55d26d455f4a4b9df32d1/src/ott/problems/quadratic/quadratic_problem.py#L225

**Comment by michalk8** [comment]
Hi @othmanesebbouh , do you suggest a different initialization or just a way to supply custom initializer in this case (for better flexibility)?

**Comment by marcocuturi** [comment]
othmane was discussing with me as we spotted this. the generic GW initializer materializes a rank 1 matrix (product of marginals) to then have this taken as a product with Cx on the left and Cy on the right. It would be more effective to save this cubic operation by computing instead (Cx a) (Cy^T b)^T using two apply and then materialize that cost. here everything remains quadratic.
