### ISSUE TITLE
Offer a way to subset (extract a few rows & cols) of potentially large cost matrices

### ISSUE THREAD

**Issue by bosr** [ott-jax/ott#209]
For some transport problems, when searching for nearest neighbors, it is useful to analyze parts of the cost matrix. Until now, version `0.3.1`, the API only offers a way to materialize and return the entire cost matrix, which is sometimes prohibitively expensive, or impossible (OOM).

I would like to API to offer a way to return only rows and columns of the cost matrix, or the documentation show how to do that.

The good news is that, for problems solved with `Sinkhorn`, extracting a few rows of the cost matrix is simple thanks to jax:

```python
geom = pointcloud.PointCloud(...)  # n points in the input domain
lin_prob = linear_problem.LinearProblem(...)
out = sinkhorn.Sinkhorn()(lin_prob)

# method 1 - full materialization then extract row k
# C = geom.cost_matrix
# C_k = C[k, :]

# alternative - extract row k
u = jnp.zeros((1,n)).at[k].set(1.0)
C_k = out.apply(u)
```

Would it make sense for you?

**Comment by michalk8** [comment]
I think there's already a way to do this as:
```python
geom = pointcloud.PointCloud(...)
C_k = geom.subset(k).cost_matrix
```

**Comment by bosr** [comment]
Oooooh

**Comment by marcocuturi** [comment]
@michalk8 , does that apply to the transport matrix? At this moment to get the `i`th line or column, i can only imagine doing an `out.apply` of that vector, with 0's and a 1. Maybe it's worth packaging a method for the user, with some indexing under the hood (a bit like when `jacobian` in jax is just a `jvp` applied to identity matrix)

**Comment by michalk8** [comment]
No, this is only for subsetting the geometry; for subsetting the transport matrix, would create another issue, but in general, I agree that we should provide some convenience methods for extracting row/columns of the transport matrix.

**Comment by bosr** [comment]
@michalk8 maybe I misread you; do you want another issue for subsetting the transport matrix? It seems to me that the current issue is the right place.

**Comment by michalk8** [comment]
> @michalk8 maybe I misread you; do you want another issue for subsetting the transport matrix? It seems to me that the current issue is the right place.

Yes, if the `geom.subset` is working as expected, let's close this issue and move the discussion for subsetting transport matrices to a new one.

**Comment by marcocuturi** [comment]
closing and reopening a new one as Michal suggested
