### ISSUE TITLE
`rank` not correctly passed in `gromov_wasserstein_make`

### ISSUE THREAD

**Issue by michalk8** [ott-jax/ott#21]
This can lead to `rank` mismatch `GromovWasserstein` class when calling:
```python
import ott
gw = ott.core.gromov_wasserstein.make(rank=4, linear_ot_solver_kwargs={"rank": 2})
print(gw.rank, gw.linear_ot_solver.rank)  # 4 2
``` 
The culprit line is here: https://github.com/ott-jax/ott/blob/master/ott/core/gromov_wasserstein.py#L354

**Comment by LaetitiaPapaxanthos** [comment]
Closing the issue, but feel free to reopen if needed.
