### ISSUE TITLE
Fix scaling by a constant

### ISSUE THREAD

**Issue by michalk8** [ott-jax/ott#212]
Seems like the newest `jax` release broke the `isinstance` [check](https://github.com/ott-jax/ott/blob/main/src/ott/geometry/geometry.py#L212).
Note  to self: we should also enable CI to run on schedule, like once/twice a week.

**Comment by michalk8** [comment]
Related to: https://jax.readthedocs.io/en/latest/jax_array_migration.html

**Comment by marcocuturi** [comment]
so it's just a question of switching to `isinstance(... jnp.Array)`?

**Comment by michalk8** [comment]
> so it's just a question of switching to isinstance(... jnp.Array)?

Yes, but need to see how backward compatible `jnp.Array` is.
