### ISSUE TITLE
Use `lax.cond` when computing error in Sinkhorn

### ISSUE THREAD

**Issue by michalk8** [ott-jax/ott#232]
Related to the below comment

> but the reason why we avoid it by default is that computing the error has the same (roughly) complexity as 1/2 sinkhorn iteration. Hence computing the error every iteration multiplies overall compute effort by 1.5, which is not reasonable

and this [TODO](https://github.com/ott-jax/ott/blob/main/src/ott/solvers/linear/sinkhorn.py#L882); although under JIT, it should be optimized away.

**Comment by marcocuturi** [comment]
Thanks and great catch :)
