### ISSUE TITLE
Some important stuff/classes are not in the ReadTheDocs

### ISSUE THREAD

**Issue by gjhuizing** [ott-jax/ott#265]
e.g. tools.plot and CostFn. Should be as simple as editing the .rst files in the docs I imagine?

**Comment by marcocuturi** [comment]
For `CostFn` it would indeed make sense to add it, because it is the template.

tools.plot also works!

**Comment by gjhuizing** [comment]
Opened a PR for this!

**Comment by michalk8** [comment]
closed via #288
