### ISSUE TITLE
Have names of class attributes created during end with a "_"?

### ISSUE THREAD

**Issue by pierreablin** [ott-jax/ott#285]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I run a sinkhorn solver `ot = sinkhorn.solve(geometry)` and the attributes of `ot` created during the solve do not end with a "_", like the sklearn convention (maybe a bad idea for this package), for instance `ot.f_` and `ot.g_`.

**Describe the solution you'd like**

Have all "fitted" attributes end with "_"

**Comment by michalk8** [comment]
I'm against this change, simply because I'm not aware of any other `jax`-based library that does this and don't think it really fits that well.

**Comment by marcocuturi** [comment]
I think the logic here is that jax objects are immutable, so strictly speaking we don't really "update" the values of `f` and `g` of an existing `SinkhornOutput` object, but rather instantiate it from scratch once the solver has finished
