### ISSUE TITLE
Potentially make matplotlib an optional dependency

### ISSUE THREAD

**Issue by ntenenz** [ott-jax/ott#292]
matplotlib is a fairly "heavy" dependency in that it pulls in lots of extra packages. Unsurprisingly, it's not truly required to use the the bulk of ott-jax outside of plotting (tools.plot, a few plotting utils in linear.potentials, and notebooks).

To allow users to leverage ott-jax without matplotlib, one could catch the ImportError and set matplotlib to None. If not calling a plotting function, things would proceed as normal. Conversely, any function that requires matplotlib could add a simple `if matplotlib is None` check (either manually or via a decorator).

This amounts to questioning how core the plotting utils are to the library. I don't think there's much, if any, harm in retaining the status quo and requiring matplotlib, but I just wanted to raise the possibility for consideration.

**Comment by michalk8** [comment]
Since #219, `jaxopt` is also a requirement and it pulls matplotlib [here](https://github.com/google/jaxopt/blob/main/requirements.txt) as well, so we'd have to make it optional as well (`jaxopt` seems to be using it only for `examples`, `docs` and `notebooks`). But I agree that plotting functions are not in the core of OTT.

**Comment by ntenenz** [comment]
Worth following this PR... https://github.com/google/jaxopt/pull/397

**Comment by michalk8** [comment]
Seems it's the same for [flax](https://github.com/google/flax/blob/main/setup.py#L30); after https://github.com/google/flax/pull/1266/files, it doesn't seem to be imported at all.

**Comment by JTT94** [comment]
I agree to make flax, jaxopt, optax optional

**Comment by ntenenz** [comment]
> I agree to make flax, jaxopt, optax optional

This feels like a much stronger statement than is being proposed in this issue. I'd recommend creating a new issue for discussion.

**Comment by ntenenz** [comment]
> Seems it's the same for [flax](https://github.com/google/flax/blob/main/setup.py#L30); after https://github.com/google/flax/pull/1266/files, it doesn't seem to be imported at all.

This looks like it should be the last of it (if solved).

```
~$ pipdeptree --reverse -p matplotlib
Warning!! Cyclic dependencies found:
* orbax => flax => orbax
* flax => orbax => flax
------------------------------------------------------------------------
matplotlib==3.7.0
  - flax==0.6.4 [requires: matplotlib]
    - orbax==0.1.1 [requires: flax]
    - ott-jax==0.4.0 [requires: flax>=0.5.2]
  - jaxopt==0.6 [requires: matplotlib>=2.0.1]
    - ott-jax==0.4.0 [requires: jaxopt>=0.5.5]
  - ott-jax==0.4.0 [requires: matplotlib>=3.0.0]
 ```

**Comment by ntenenz** [comment]
FYI @michalk8, flax has now made matplotlib optional (it is now behind a [all] flag). As a result, it shouldn't be pulled in following the next flax release.
