### ISSUE TITLE
Follow up on issue #6 of archived repo https://github.com/google-research/ott

### ISSUE THREAD

**Issue by ersisimou** [ott-jax/ott#3]
Hello,

This is a follow up to [this issue](https://github.com/google-research/ott/issues/6) (currently read-only) from the previous development branch of this toolbox.

It was suggested there that if we would like to check whether Sinkhorn has run without numerical issues, we should check the out.converged and/or the out.errors.

In the case however, where the call to the sinkhorn function is included in another function (which we would like to jax.jit), checking out.converged and/or out.errors raises a ``ConcretizationTypeError``.

I share [here ](https://colab.research.google.com/drive/1odN6B82cexGXLpKBUBL7XmJ0NEGOGbMW?usp=sharing)a collab demonstrating the issue.

Are there any pointers as to how this could be avoided?

Thanks in advance.

**Comment by marcocuturi** [comment]
Hi Ersi! thanks for your comment.

A way to avoid the error you mention would be to replace the
```
if out.errors[-1] < 1 and out.converged:
 return out.reg_ot_cost
```

statement in your function by a conditional statement that is jit compatible, in this case this could be
```
  return jnp.where(out.converged, out.reg_ot_cost, jnp.nan)
```
PTAL at your modified colab:
https://colab.research.google.com/drive/1riWnktM6HwTxzCJp3_dRMH0h4NVcU7m9#scrollTo=uK5zdU44J8it
