### ISSUE TITLE
Make flax, optax, jaxopt optional dependencies

### ISSUE THREAD

**Issue by JTT94** [ott-jax/ott#307]
Flax, optax, jaxopt to my understanding are only required for neural network based OT. 

There may be situations whereby these are not needed. For example if some users prefer to use haiku instead of flax or just require sinkhorn and not icnn or nn initializers. 

It seems like overkill to require users install these. I do not think these are installed by default in colab for example. 

Any opinions?

**Comment by michalk8** [comment]
For now, I'd keep these dependencies as to provide a reference implementation, but in the future, I can imagine users using their NN models/optimizers not tied to `flax/optax`.

**Comment by JTT94** [comment]
Yeah I agree, not a priority.
