### ISSUE TITLE
GPU Memory consumption

### ISSUE THREAD

**Issue by Joseph-Chen-Jh** [ott-jax/ott#352]
**Describe the bug**
ott occupies around 70% of GPU memory even if no calculation is going on.

**To Reproduce**
I'm using ott-jax==0.2.11 to compute sinkhorn, on Geforce RTX3090. I found that around 17000MiB of gpu memory is immediately occupied right after  "import ott" or when any sub-module of ott is imported. The resources are not released until the whole program terminate.  

I'm using CUDA Version 11.4 + cudnn82. I also tried ott-jax version 0.3.1 and turned out the same.

**Expected behavior**
I thought such large amount of memories should only be taken when actual calculations are going on. I'm only using ott-jax in part of my program, is there any method to release the memory when ott is not called on?  Is it a bug or is it the feature of ott-jax? 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu20.04.1

**Smartphone (please complete the following information):**

**Additional context**

**Comment by michalk8** [comment]
By default, `jax`, pre-allocated 90% of the GPU memory when the first operation is run, see [here](https://jax.readthedocs.io/en/latest/gpu_memory_allocation.html).
I assume it's because we initialize random keys as the default arguments for certain methods which can cause this (see https://github.com/google/jax/issues/5181).

**Comment by marcocuturi** [comment]
Yes, I think this makes sense! then maybe test if None then default to PRNGKey(0)?

**Comment by Joseph-Chen-Jh** [comment]
Thanks! In that case I decide to simply separate the jax part from main program 
 : )
