### ISSUE TITLE
Bug in Sinkhorn Barycenter notebook

### ISSUE THREAD

**Issue by solevillar** [ott-jax/ott#356]
This notebook https://github.com/ott-jax/ott/blob/main/docs/tutorials/notebooks/Sinkhorn_Barycenters.ipynb
calls the FixedBarycenterProblem incorrectly

<img width="1026" alt="Screen Shot 2023-04-24 at 3 17 28 PM" src="https://user-images.githubusercontent.com/17749998/234007955-a2155b40-c3c6-406a-9090-4f48eaf6cfe2.png">

**Comment by michalk8** [comment]
> This notebook https://github.com/ott-jax/ott/blob/main/docs/tutorials/notebooks/Sinkhorn_Barycenters.ipynb
calls the FixedBarycenterProblem incorrectly

Thanks for catching this; it should be `db.FixedBarycenter`, not `db.FixedBarycenterProblem`.
