### ISSUE TITLE
converged flag in `SinkhornOutput` is not reliable.

### ISSUE THREAD

**Issue by marcocuturi** [ott-jax/ott#375]
`converged` flag of `SinkhornOutput` in sinkhorn checks if the last `error` entry is -1 

https://github.com/ott-jax/ott/blob/05c0afb6416329c563ed0074c7bcbb7fe50feceb/src/ott/solvers/linear/sinkhorn.py#L368C11-L368C11

but this is a wrong way to test if the number of iterations is defined ahead, as in `min_iterations=max_iterations= N` (which triggers a `scan_loop` rather than a `fixed_point_iter`)

**Comment by solevillar** [comment]
I believe the same occurs in line 259 of 
https://github.com/ott-jax/ott/blob/05c0afb6416329c563ed0074c7bcbb7fe50feceb/src/ott/solvers/quadratic/gromov_wasserstein.py

Would it be possible to fix that too?
