### ISSUE TITLE
JAX Concretization error when jitting sinkhorn with non-static tau_a, tau_b

### ISSUE THREAD

**Issue by haeggee** [ott-jax/ott#388]
**Describe the bug**
Attempting to jit the sinkhorn algorithm for non-static `tau_a` or `tau_b` (i.e. unbalanced OT) throws a concretization error, as the solver uses the two parameters to assess if the problem is balanced (via `self.tau_a == 1.0 and self.tau_b == 1.0`, see the line [here](https://github.com/ott-jax/ott/blob/f55eb8ea2c8120e02d6cdfd63e8c0a32614776b9/src/ott/problems/linear/linear_problem.py#L79)).

**To Reproduce**
```python
import ott, jax

def mysink(x, y, tau_a):
    geom = ott.geometry.pointcloud.PointCloud(x,y)
    prob = ott.problems.linear.linear_problem.LinearProblem(geom=geom,tau_a=tau_a)
    return ott.solvers.linear.sinkhorn.Sinkhorn()(prob).reg_ot_cost

x = jax.random.uniform(jax.random.PRNGKey(0), (12,3))
y = jax.random.uniform(jax.random.PRNGKey(1), (16,3))

# this works fine, but recompiles at every call
mysink(x,y,1.0)

# this will cause a concretization error when the solver calls ot_prob.is_balanced
jax.jit(mysink)(x,y,1.0)

# a workaround is having tau_a as a static argument, but causes recompilation for different values
jax.jit(mysink, static_argnums=(2,))(x,y,1.0)

```

**Full Stacktrace**
<details>
  <summary>
    Click to expand
  </summary>

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 4, in mysink
  File "/Users/ahaegele/Projects/ott/src/ott/solvers/linear/sinkhorn.py", line 833, in __call__
    return run(ot_prob, self, (init_dual_a, init_dual_b))
  File "/Users/ahaegele/Projects/ott/src/ott/solvers/linear/sinkhorn.py", line 1086, in run
    out = iter_fun(ot_prob, solver, init)
  File "/Users/ahaegele/Projects/ott/src/ott/solvers/linear/sinkhorn.py", line 1123, in iterations
    state = fix_point(
  File "/Users/ahaegele/Projects/ott/src/ott/math/fixed_point_loop.py", line 92, in fixpoint_iter
    _, state = jax.lax.while_loop(max_cond_fn, unrolled_body_fn, (0, state))
  File "/Users/ahaegele/Projects/ott/src/ott/math/fixed_point_loop.py", line 80, in unrolled_body_fn
    iteration_state, _ = jax.lax.scan(
  File "/Users/ahaegele/Projects/ott/src/ott/math/fixed_point_loop.py", line 76, in one_iteration
    state = body_fn(iteration, constants, state, compute_error)
  File "/Users/ahaegele/Projects/ott/src/ott/solvers/linear/sinkhorn.py", line 1111, in body_fn
    return solver.one_iteration(ot_prob, state, iteration, compute_error)
  File "/Users/ahaegele/Projects/ott/src/ott/solvers/linear/sinkhorn.py", line 946, in one_iteration
    err = jax.lax.cond(
  File "/Users/ahaegele/Projects/ott/src/ott/solvers/linear/sinkhorn.py", line 948, in <lambda>
    lambda state, prob: state.solution_error(
  File "/Users/ahaegele/Projects/ott/src/ott/solvers/linear/sinkhorn.py", line 79, in solution_error
    return solution_error(
  File "/Users/ahaegele/Projects/ott/src/ott/solvers/linear/sinkhorn.py", line 167, in solution_error
    if ot_prob.is_balanced and not parallel_dual_updates:
  File "/Users/ahaegele/Projects/ott/src/ott/problems/linear/linear_problem.py", line 79, in is_balanced
    return self.tau_a == 1.0 and self.tau_b == 1.0
jax.errors.ConcretizationTypeError: Abstract tracer value encountered where concrete value is expected: traced array with shape bool[].
The problem arose with the `bool` function.
The error occurred while tracing the function <lambda> at /Users/ahaegele/Projects/ott/src/ott/solvers/linear/sinkhorn.py:948 for cond. This value became a tracer due to JAX operations on these lines:

  operation a:bool[] = eq b c
    from line /Users/ahaegele/Projects/ott/src/ott/problems/linear/linear_problem.py:79 (is_balanced)

See https://jax.readthedocs.io/en/latest/errors.html#jax.errors.ConcretizationTypeError
```

</details>

**Expected behavior**
Generally, I do not think it should be needed to have `tau_a` or `tau_b` be static. The `is_balanced` seems to be mostly used as a way to speed up some computations (but maybe there are some places where there is a more intricate switch between the problems, e.g. GW). Having to define `tau_a` as a static argument causes recompilation every time the parameter is changed.

**Additional context**
Another fix could be to have the user define a boolean argument `is_balanced=True` to the problem such that no dynamic check is be needed. This would only cause compilation for `True` and `False`, if needed.

I'd be happy to look into this myself and possibly open a PR depending on what you think.

Thanks!

**Comment by michalk8** [comment]
Currently, `tau_{a,b}` cannot be traced. Is there any reason you want these to be traced, i.e., you wanna differentiate w.r.t. to `tau_{a,b}`?

> Having to define tau_a as a static argument causes recompilation every time the parameter is changed.

How often do you need to recompile in your use-case?

>  Another fix could be to have the user define a boolean argument is_balanced=True to the problem such that no dynamic check is be needed. This would only cause compilation for True and False, if needed.

I feel this would be really error-prone; what's possible would be to allow `tau_{a,b}` to be both static or dynamic (checking this at compile time with `jax`) and then use either Python `if` or `jax.lax.cond` (this is more complicated that it being just static/dynamic).

**Comment by haeggee** [comment]
In my use case, I do not actually want to differentiate w.r.t. `tau_{a,b}`. I was investigating the effect of the two variables on the result of Sinkhorn; trying to use `jit` and different values led me to the problem above.

I agree, the `jax.lax.cond` way is probably the most rigorous one. I just thought this would require a more involved rewrite and might (unnecessarily?) complicate the backend. 

In any case, this is not a very pressing issue. Maybe we can keep it in mind and introduce the dynamic version when there is more need for it in the future.

**Comment by marcocuturi** [comment]
I think it's good to keep in mind that the `tau_a` and `tau_b` will need to be kept static, maybe it's simpler this way for now. I can imagine use cases where one might want to differentiate against them though... we can revisit this then
