### ISSUE TITLE
have a `solve()` method for `sinkhorn_lr`

### ISSUE THREAD

**Issue by marcocuturi** [ott-jax/ott#401]
the `sinkhorn` module implements a `solve()` wrapper that can be helpful to avoid instantiating a solver. Maybe we should have the same thing for `sinkhorn_lr` (and maybe, by extension, all other solvers?)

**Comment by michalk8** [comment]
This is already implemented in `ott.solvers.linear.sinkhorn.solve(..., rank=-1)` by passing `rank != -1`. Do you wanna split it? Personally, am ok with splitting it.

**Comment by marcocuturi** [comment]
thanks! had forgotten about this.

i feel then that this unified wrapper should be called something else than sinkhorn. Maybe something more generic, e.g. ott.solvers.linear.solve() ?

and we could think about the same thing with GW?

**Comment by michalk8** [comment]
I think putting it directly in `linear` makes sense.

**Comment by marcocuturi** [comment]
I think your solution was very elegant. We might do it with the `quadratic` branch as well?

**Comment by michalk8** [comment]
closed in favor of #432
