### ISSUE TITLE
Possibly make neural network packages as optional dependencies

### ISSUE THREAD

**Issue by MUCDK** [ott-jax/ott#409]
Some jax packages are still very unstable and cause installation problem. E.g. [flax has no conda release for v0.7.x](https://github.com/conda-forge/flax-feedstock/pull/28), causing many issues for installation. 

A solution would be to make flax, optax, etc. optional dependencies.

As deep learning based OT method might need further additional packages in future times, it would probably make sense to make them all optional.

**Comment by JTT94** [comment]
Related: https://github.com/ott-jax/ott/issues/307#issue-1589470571
