### ISSUE TITLE
pre-commit

### ISSUE THREAD

**Issue by michalk8** [ott-jax/ott#43]
I'd like to suggest using a [pre-commit](https://pre-commit.com/) to mostly unify formatting/add ome simple checks.

For starters, I'd recommend the following:
- [black](https://github.com/psf/black): for formatting (also would switch to 4 spaces instead of 2)
- [isort](https://pycqa.github.io/isort/): to sort imports
- the following hooks from https://github.com/pre-commit/pre-commit-hooks:
  - [check-ast](https://github.com/pre-commit/pre-commit-hooks#check-ast) so that valid Python code is committed
  - [check-merge-conflict](https://github.com/pre-commit/pre-commit-hooks#check-merge-conflict) to not commit files where a merge conflict is present
  - end of line/whitpace handlers: [end-of-file-fixer](https://github.com/pre-commit/pre-commit-hooks#end-of-file-fixer), [trailing-whitespace](https://github.com/pre-commit/pre-commit-hooks#trailing-whitespace) [mixed-line-ending](https://github.com/pre-commit/pre-commit-hooks#mixed-line-ending)

Example file I like using is here, though there are other checks, such as for typing and documentation: https://github.com/theislab/squidpy/blob/master/.pre-commit-config.yaml
`black`/`isort` are configured here: https://github.com/theislab/squidpy/blob/master/pyproject.toml#L5-L58

For new contributors, the workflow would then be:
```bash
git clone https://github.com/ott-jax/ott && cd ott
pip install -e'.[dev]'  # extra `dev` requirements contains `pre-commit` package
pre-commit install
```

**Comment by marcocuturi** [comment]
Hi Michal
> [black](https://github.com/psf/black): for formatting (also would switch to 4 spaces instead of 2)

I think the 4 spaces makes life more difficult when sticking to the 80 characters / line rule. Since the entire codebase is written with 2 spaces, I think I'd rather stick to 2 :) 

> Example file I like using is here, though there are other checks, such as for typing and documentation: https://github.com/theislab/squidpy/blob/master/.pre-commit-config.yaml
> black/isort are configured here: https://github.com/theislab/squidpy/blob/master/pyproject.toml#L5-L58
 
This sounds good! So we only need to add your `.pre-commit-config.yaml` to the repo, right? please go ahead with a PR, I am happy to validate it.

**Comment by marcocuturi** [comment]
That sounds like a good idea! I am not sure it is customary to add the .gitignore in the github folder, but it does indeed make life a bit easier for people that fork and want to send a PR for the first time. If you think it's usual I am happy to add it too if you send a PR!
