### ISSUE TITLE
`threshold` and `max_iter` parameters for LR-OT

### ISSUE THREAD

**Issue by feiyang-k** [ott-jax/ott#435]
Hi,

Thanks to the detailed help, now I think I have figured out the solution process for LR-UOT. It works really well!

It seems the same process does not apply to the balanced case, LR-OT. I don't think the parameters I passed in `kwargs_dys` such as 
> solver = sinkhorn_lr.LRSinkhorn(rank=int(200), progress_fn=progress_fn, kwargs_dys={"threshold":0.1, "max_iter":100})

are functioning. The errors printed out by the callback reach `0.000000e+00` early on, but the iteration will keep progressing towards `200`. The workaround I found is to set it to an imbalanced case such as with `tau_a=0.999, tau_b=0.9999`, where `kwargs_dys` works. I'm not sure if the per-iter time is the same (but at least it seems so).

By the way, in the `tqdm` progression bar, the end goal always displays `200`. But the progression speed is visibly different so I know when `"max_iter"` is working.

Thanks!

**Comment by michalk8** [comment]
> It seems the same process does not apply to the balanced case, LR-OT. I don't think the parameters I passed in kwargs_dys such as

They should be functioning correctly, as they control the **inner** Dykstra loop. The progress bar shows errors the **outer** loop.

>  The errors printed out by the callback reach 0.000000e+00 early on, but the iteration will keep progressing towards 200.

I will re-check the [convergence](https://github.com/ott-jax/ott/blob/main/src/ott/solvers/linear/sinkhorn_lr.py#L778-L803) criteria (we use some heuristics to get out of a local minima at the start).
Could you please plot the errors like as:
```python
import matplotlib.pyplot as plt

solver = ...
out = solver(...)

plt.plot(out.errors)
```

> By the way, in the tqdm progression bar, the end goal always displays 200. But the progression speed is visibly different so I know when "max_iter" is working.

Passing `kwargs_dys={"max_iter": ...}` controls the Dykstra inner loop. The control the outer loop are, you can pass, e.g., `LRSinkhorn(..., min_iteraions=0, max_iterations=2000,
inner_iterations=10)`, meaning the error is evalues `max_iterations // inner_iterations` times.
