### ISSUE TITLE
Epsilon = 1.0 in Graph geometry

### ISSUE THREAD

**Issue by gjhuizing** [ott-jax/ott#470]
Hello!

I was playing with the Graph geometry today and I noticed epsilon=1.0 is hardcoded, is there a reason for that?

https://github.com/ott-jax/ott/blob/75cdd117871110017e50b0240f886700477e4674/src/ott/geometry/graph.py#L59C1-L59C43

Best,

GJ

**Comment by marcocuturi** [comment]
Hi Geert-Jan! 
easy answer is that the graph geometry, as implemented, using a heat kernel approximation. The kernel is directly implemented, and applied. Therefore this is not a `exp(-C/eps)` type application, but directly a `K` application.  In fact, that geometry does not parameterize `C,epsilon` , just a `K` directly. `epsilon` is passed on by default as `1.0` to be consistent.

**Comment by gjhuizing** [comment]
Very clear, thank you Marco!
