### ISSUE TITLE
`converged` flag compatibility with `min_iterations` logic

### ISSUE THREAD

**Issue by zoepiran** [ott-jax/ott#495]
**Describe the bug**
1. Given `min_iterations > inner_iterations` the final costs array will contain `inf`s ([710, 717-720, 731](https://github.com/ott-jax/ott/blob/036add26e4f4391479905e71df910f691f94478c/src/ott/solvers/quadratic/gromov_wasserstein_lr.py#L710-L731)).
2. The `inf`s imply `converged=False` following _all_is_finite_  condition ([201](https://github.com/ott-jax/ott/blob/036add26e4f4391479905e71df910f691f94478c/src/ott/solvers/quadratic/gromov_wasserstein_lr.py#L201)).

**To Reproduce**
```{python}
rngs = jax.random.split(jax.random.PRNGKey(0), 4)
n, m, d1, d2 = 5_000, 2_500, 1, 2
x = jax.random.uniform(rngs[0], (n, d1))
y = jax.random.uniform(rngs[1], (m, d2))
xx = jax.random.uniform(rngs[2], (n, d2))
yy = jax.random.uniform(rngs[3], (m, d2))

geom_x = PointCloud(x)
geom_y = PointCloud(y)
geom_xy = PointCloud(xx, yy)
prob = QuadraticProblem(geom_x, geom_y, geom_xy)
solver = jax.jit(LRGromovWasserstein(
     rank=2, 
     min_iterations=100, 
     inner_iterations=10, 
     max_iterations=2_000,
     progress_fn = utils.default_progress_fn()
))

ot_gwlr = solver(prob)

print(f"converged? {ot_gwlr.converged}")
print(f"costs:{ot_gwlr.costs[np.where(ot_gwlr.costs != -1)[0]]}")
```

**Expected behavior**
Convergence evaluation will ignore `cost` values not computed. 

**Screenshots**
![Screenshot 2024-02-27 at 12 15 49](https://github.com/ott-jax/ott/assets/43661890/2dc833ca-8819-40c0-848d-6223299e12bc)

**Comment by michalk8** [comment]
Thanks for spotting this, indeed should be fixed

**Comment by giovp** [comment]
I tried with the code above

<details>
<summary>Details</summary>

```python
from ott.geometry.pointcloud import PointCloud
from ott.problems.quadratic.quadratic_problem import QuadraticProblem
from ott.solvers.quadratic.gromov_wasserstein_lr import LRGromovWasserstein
import jax
from ott import utils
import numpy as np

rngs = jax.random.split(jax.random.PRNGKey(0), 4)
n, m, d1, d2 = 5_000, 2_500, 1, 2
x = jax.random.uniform(rngs[0], (n, d1))
y = jax.random.uniform(rngs[1], (m, d2))
xx = jax.random.uniform(rngs[2], (n, d2))
yy = jax.random.uniform(rngs[3], (m, d2))

geom_x = PointCloud(x)
geom_y = PointCloud(y)
geom_xy = PointCloud(xx, yy)
prob = QuadraticProblem(geom_x, geom_y, geom_xy)
solver = jax.jit(LRGromovWasserstein(
     rank=2, 
     min_iterations=100, 
     inner_iterations=10, 
     max_iterations=2_000,
     progress_fn = utils.default_progress_fn()
))

ot_gwlr = solver(prob)

print(f"converged? {ot_gwlr.converged}")
print(f"costs:{ot_gwlr.costs[np.where(ot_gwlr.costs != -1)[0]]}")
```

</details>

I noticed that sometime I get all `inf` and still convergence=True
```
converged? True
costs:[inf inf inf inf inf inf inf inf inf inf]
```
what would be the right solution for raising the convergence flag correctly?

**Comment by zoepiran** [comment]
I can't figure what actually happens here as the converged flag is still set using the same condition ([here](https://github.com/ott-jax/ott/blob/c0a61e8367483ee69c2652064f8ec580e3a2fccd/src/ott/solvers/quadratic/gromov_wasserstein_lr.py#L198C1-L201C6)):

```
 def converged(self) -> bool:  # noqa: D102
    return jnp.logical_and(
        jnp.any(self.costs == -1), jnp.all(jnp.isfinite(self.costs))
    )
```

Other than that the appearance of exactly 10 `inf`s makes sense, given the construction in [one_iteration()](https://github.com/ott-jax/ott/blob/036add26e4f4391479905e71df910f691f94478c/src/ott/solvers/quadratic/gromov_wasserstein_lr.py#L688)
as long as `iteration < self.min_iterations` an `inf` is set.
