### ISSUE TITLE
Sinkhorn iteration is not converging in A100 GPU

### ISSUE THREAD

**Issue by yexf308** [ott-jax/ott#496]
I have tried the following code in A100 and other GPU. I found in other GPU, such as T4, V100, A40, this Sinkhorn iteration will converge, but in A100 GPU, the Sinkhorn iteration is stuck in some value until the maximum iteration is reached. Do anyone know what happened here? 

**To Reproduce in A100 GPU**
``` python
n           = 50
𝜀           = 1
threshold   = 0.01

threshold   = 1e-2
blob_std    = 1

x, data_mem   = make_blobs(n_samples=n, n_features=4, centers=1, cluster_std=blob_std, random_state=1)
mu                 = np.ones((n,)) / n # size of M
nv                  = np.ones((n,)) / n # size of N
w                    = np.random.normal(size=[4,2])
w_int               = w + 1 * np.random.normal(size=[4,2])
y                      = x.dot(w) + 1 * np.random.normal(size=[n,2])
y_pred            = x.dot(w_int)
y_jx                = jnp.array(y)
pred_jx          = jnp.array(y_pred)

from ott import utils
geom = pointcloud.PointCloud(pred_jx, y_jx, epsilon=𝜀)
prob = linear_problem.LinearProblem(geom, a=mu, b=nv)
solver = sinkhorn.Sinkhorn(
        threshold=threshold, inner_iterations=200, lse_mode=True, max_iterations=1000, 
        norm_error=1,use_danskin=False, progress_fn=utils.default_progress_fn()
    )
out = solver(prob)
```

The screenshot of the output in A100 is 
<img width="332" alt="Screenshot 2024-03-01 at 11 43 32 AM" src="https://github.com/ott-jax/ott/assets/1251465/81ea805a-a043-4c1b-8789-857e0692a149">

**Comment by yexf308** [comment]
The screenshot of the output in T4 is
<img width="331" alt="Screenshot 2024-03-01 at 11 52 46 AM" src="https://github.com/ott-jax/ott/assets/1251465/f0778281-6558-4c45-b8fe-51e154bb9b93">

**Comment by michalk8** [comment]
Hi @yexf308 , I can reproduce the above on A100 using:
<img width="781" alt="image" src="https://github.com/ott-jax/ott/assets/46717574/2f38b0c9-2a36-4fe4-b21f-fc7f40fda32c">

As for the reason, I think there are things at play:
1. The values of in the cost matrix is really big, it's in around `[0.15, 417]`, which can lead to numerical instability. One way to solve this is to scale the cost matrix, e.g., by the mean as `scale_cost='mean'`. Other solution is to use 64-bit precision.
2. XLA seems to generate different code for CPU/GPU/other accelerators, so I assume this is where the CPU/GPU discrepancy comes in; unfortunately this is out of our control

**Comment by yexf308** [comment]
@michalk8 I have checked `out.matrix` and compared with the output error. The `out.matrix` is actually converged to desired coupling matrix within the threshold, the error calculating is actually in-correct. That is why I suspect there is some bugs. Thanks for the quick reply!

**Comment by yexf308** [comment]
Here is the screenshot. 

<img width="1041" alt="Screenshot 2024-03-01 at 12 52 35 PM" src="https://github.com/ott-jax/ott/assets/1251465/77a052b4-7e3e-40c4-ab57-f071527217c0">

**Comment by yexf308** [comment]
This issue is resolved if one uses double precision.
