### ISSUE TITLE
Misnumbered equation

### ISSUE THREAD

**Issue by gjhuizing** [ott-jax/ott#513]
Hi!

This is a tiny detail, but it seems the preprint was updated and that equation 24 has changed.

https://github.com/ott-jax/ott/blob/e1bbd34aaa6c003258912caf478bbfd718a750a0/src/ott/solvers/linear/sinkhorn.py#L278

https://arxiv.org/pdf/1910.12958v2.pdf has the right equation though.

While I'm at it, in the Sinkhorn docs, https://ott-jax.readthedocs.io/en/latest/solvers/_autosummary/ott.solvers.linear.sinkhorn.Sinkhorn.html, shouldn't it be +g in eq 1, and +KL in eq 3?

Best

GJ

**Comment by michalk8** [comment]
Thanks @gjhuizing for noticing this, closed via #548
