### ISSUE TITLE
Pin JAX/jaxlib version

### ISSUE THREAD

**Issue by MUCDK** [ott-jax/ott#552]
While we are testing for the "default" and the latest jax version, would it be possible to pin JAX/jaxlib to the "default" version?

This would make it easier for non-experienced users of downstream libraries.

**Comment by michalk8** [comment]
Unfortunately, I don't want to pin a specific `jax/jaxlib` version, it's too restrictive. Having a lower bound on the pin + testing also for the latest should be sufficient.
