### ISSUE TITLE
Vmap-based parallelization possible with variable sized inputs?

### ISSUE THREAD

**Issue by sankethvedula** [ott-jax/ott#573]
Hi,

Apologies if this is a trivial question; I couldn't find a simple answer in the docs/tutorials, I thought I could ask for your input.

I would like to solve variably-sized linear entropic OT problems in a _batch_.

Assume I have $N$ cost matrices $\mathbf{C}=[\mathbf{C}_1,\ldots,\mathbf{C}_N]$, that are _not_ of the same shape. Similarly I have appropriately-sized marginals, $[a_1,\ldots,a_N]$ and $[b_1,\ldots,b_N]$, for each such OT problem.

Would it be possible to `vmap` the Sinkhorn solver to solve these problems in parallel with `ott`?

I read this [tutorial](https://ott-jax.readthedocs.io/en/latest/tutorials/linear/000_One_Sinkhorn.html). If I understand correctly, it shows how to vmap to solve several _same sized_ OT problems, but I have not seen an instance where one solves differently-sized OT problems. Could you please let me know if I missed something?

Thanks!

**Comment by marcocuturi** [comment]
hi Sanketh, we're sorry for the very delayed answer.

I think you want to look at this : https://ott-jax.readthedocs.io/en/latest/_autosummary/ott.tools.segment_sinkhorn.segment_sinkhorn.html

we haven't written a tutorial for this functionality... but as usual, you can find proto-tutorials in tests:
https://github.com/ott-jax/ott/blob/main/tests/tools/segment_sinkhorn_test.py

Thanks again and apologies for not being more reactive!

**Comment by sankethvedula** [comment]
Thanks @marcocuturi! This looks to be exactly what I need. I'll give it a shot and post here if it works, so it could be useful for future users.

**Comment by marcocuturi** [comment]
@sankethvedula all good on this or shall we close the issue?
