### ISSUE TITLE
How to build an iterable DataLoader for a pre-existing dataset

### ISSUE THREAD

**Issue by tuln128** [ott-jax/ott#59]
Dear the authors of OTT,
I am interested in learning a Kantorovich dual using ICNN (mentioned here https://ott-jax.readthedocs.io/en/latest/notebooks/neural_dual.html). However, in the given example, the dataloaders were created for a data generator, which maybe different from the common usage in which data are read from some existing sources. In such case (the data for training are pre-existed), **how should the dataloaders be defined and input into the solver to get the neural dual**?
Looking forward to your explanation.
Thank you very much!

**Comment by bunnech** [comment]
Dear @[tuln128](https://github.com/tuln128),

you can use any dataloader framework for your input dataset which returns an iterator. The NeuralDual of OTT calls the next() function which returns the next item from the iterator.

Best,
Charlotte

**Comment by tuln128** [comment]
Dear @bunnech,

Thank you very much for your prompt feedback. I am still a bit confused about how the **num_train_iters** parameter of **NeuralDualSolver** is related to the iteration on the training data. For example, while I tried the following codes, it threw back a "StopIteration" error message. Could you please show me why it caused such error, or it would be great if you can provide some sample test codes for this use case. 

# initialize parameters
num_of_source_instances = 1000
num_of_target_instances = 800
n_dims = 30
batch_size = 10

# generate sample data
source_data = torch.from_numpy(np.random.randn(num_of_source_instances,n_dims))
target_data = torch.from_numpy(np.random.randn(num_of_target_instances,n_dims))

dataloader_source = iter(DataLoader(source_data, batch_size))  
dataloader_target = iter(DataLoader(target_data, batch_size))

# initialize models
neural_f = icnn.ICNN(dim_hidden=[64, 64])
neural_g = icnn.ICNN(dim_hidden=[64, 64])

# initialize optimizers
optimizer_f = get_optimizer('Adam', lr=0.0001, b1=0.5, b2=0.9, eps=0.00000001)
optimizer_g = get_optimizer('Adam', lr=0.0001, b1=0.5, b2=0.9, eps=0.00000001)

neural_dual_solver = NeuralDualSolver(n_dims, neural_f, neural_g, optimizer_f, optimizer_g, num_train_iters=10)

neural_dual = neural_dual_solver(
dataloader_source, dataloader_target, dataloader_source, dataloader_target)

Thank you very much for your kind support, and sorry for bothering.

Best,

**Comment by bunnech** [comment]
Because you exhausted your iterator. You need to adapt the `num_train_iters` as well as `batch_size` to your dataset. As this is independent of OTT, please have a look for example at the PyTorch's [documentation](https://pytorch.org/docs/stable/data.html#data-loading-order-and-sampler) on that topic.

**Comment by tuln128** [comment]
Dear @bunnech 
Thanks for clarifying and your kind support. I will try the option you suggested.
Best,
