### ISSUE TITLE
Can this repository support batched OT calculation?

### ISSUE THREAD

**Issue by jsttlgdkycy** [ott-jax/ott#593]
Hi,

Thank you for your work! I'm currently facing a challenge where I got a fixed transport cost matrix with shape n*n, while having many different marginal distributions $a$ and $b$ with shape [B, n] (B is the batch size). I would like to know if this codebase can solve these problems in parallel. Thank you!

**Comment by marcocuturi** [comment]
Yes, it's possible, but to ensure that you get proper parallelization / a speed-up you need to ensure that the number of Sinkhorn iterations is fixed in advance. This is described here (Ctrl+F "vmap") 

https://ott-jax.readthedocs.io/en/latest/tutorials/linear/000_One_Sinkhorn.html

**Comment by marcocuturi** [comment]
@jsttlgdkycy, could you make this work? happy to help if this is not working as you expect!

**Comment by jsttlgdkycy** [comment]
Hi @marcocuturi, I tried the example in https://ott-jax.readthedocs.io/en/latest/tutorials/linear/000_One_Sinkhorn.html#pairwise-sinkhorn, and it worked! Now I'm trying to adapt it to my own code. Thanks again for your help!

**Comment by marcocuturi** [comment]
Thanks @jsttlgdkycy ! glad to know it worked :) closing the issue then.
