### ISSUE TITLE
Wrong implementation of u_t(x|z) in Brownian Bridge

### ISSUE THREAD

**Issue by selmanozleyen** [ott-jax/ott#595]
Hi,
I was reading the tong et al 23 paper and noticed the implementation might be wrong here. As I was using this flow for my thesis project already.

In the implementation ut() = x1-x0 but in the paper it is
![image](https://github.com/user-attachments/assets/039e6014-efc4-43fa-bcfb-9752d5a48263)

https://github.com/ott-jax/ott/blob/828acca41a0c41ce38440ad51896e5c29161cbbd/src/ott/neural/methods/flows/dynamics.py#L143

**Comment by MUCDK** [comment]
Good point @selmanozleyen , can you open a PR?
