### ISSUE TITLE
First example in docs doesn't load `ott.tools.plot`

### ISSUE THREAD

**Issue by adrhill** [ott-jax/ott#74]
The [first example](https://ott-jax.readthedocs.io/en/latest/notebooks/point_clouds.html#Visualizes-the-transport) in the docs cannot be copy-pasted:
 ```python
 plott = ott.tools.plot.Plot()
_ = plott(ot)
```
```
AttributeError: module 'ott.tools' has no attribute 'plot'
```
 This could be fixed by uncommenting the following import in `ott/tools/__init__.py`:
https://github.com/ott-jax/ott/blob/8c512e57c83932b74d60671f10b08cf7535d587c/ott/tools/__init__.py#L18
or by adding `import ott.tools.plot` to the docs page.

**Comment by marcocuturi** [comment]
Adrian, thanks a lot for pointing this out! 
will solve this shortly after 1PM PST today :)

**Comment by marcocuturi** [comment]
should be solved with commit https://github.com/ott-jax/ott/commit/991515a0359954f23899a7489bb6dc3494e99ed1
