### ISSUE TITLE
catching `online=True` in `gromov_wasserstein`

### ISSUE THREAD

**Issue by zoepiran** [ott-jax/ott#79]
hi,
we noticed that one can accidentally pass `online=True` using `gromov_wasserstein` and this will propagate through `**kwargs`. Eventually mapping will fail at some point due to dimensionality assertion but we thought it may be useful to catch it earlier and warn. 
What do you think?

**Comment by marcocuturi** [comment]
So I guess there are two options:
- do nothing, but at least it does fail (so it's not a silent error)
- pass a warning message? I feel that if we do this we might have to do it for other parameter selections that may not be always necessarily valid.

**Comment by zoepiran** [comment]
First of all, maybe an intermediate resolution is to add some `docs`, because from the manner it fails the user cant really understand this is the source. In addition, in an extreme situation it may be that the `shape`s are such that it won't fail. 
And, maybe worth thinking which parameters we should check for to ensure valid GW ?

**Comment by marcocuturi** [comment]
another option could be to drop it explicitly (i.e. pop it from kwargs and replace by False)?

**Comment by zoepiran** [comment]
yes. probably easiest.

**Comment by zoepiran** [comment]
together with @michalk8 found the source of the original failure (misusage of `jnp.where`). @michalk8 wants to allow `online` for GW and will fix accordingly
