### ISSUE TITLE
Add init to the solver

### ISSUE THREAD

**Issue by JTT94** [ott-jax/ott#84]
https://github.com/ott-jax/ott/blob/710f807f17b15edc6bc941ad4f760656059e6beb/ott/tools/transport.py#L128

solver wrapper missing init args, silent error if passing init_dual_a, init_dual_b in kwargs

**Comment by marcocuturi** [comment]
I think this approach could be extend to provide initializations for barycenter problems. Is there a common API we should think about for `SinkhornInitializer` and more general initializers (LR Sinkhorn, GW, GW-LR, (F)(G)W barycenters etc...)

**Comment by marcocuturi** [comment]
solved with #98
